
package files;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ConversionServlet", targetNamespace = "http://com")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ConversionServlet {


    /**
     * 
     * @param value
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(name = "convertMilesToKilometersReturn", targetNamespace = "http://com")
    @RequestWrapper(localName = "convertMilesToKilometers", targetNamespace = "http://com", className = "com.ConvertMilesToKilometers")
    @ResponseWrapper(localName = "convertMilesToKilometersResponse", targetNamespace = "http://com", className = "com.ConvertMilesToKilometersResponse")
    public double convertMilesToKilometers(
        @WebParam(name = "value", targetNamespace = "http://com")
        double value);

    /**
     * 
     * @param value
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(name = "convertFeetToMilesReturn", targetNamespace = "http://com")
    @RequestWrapper(localName = "convertFeetToMiles", targetNamespace = "http://com", className = "com.ConvertFeetToMiles")
    @ResponseWrapper(localName = "convertFeetToMilesResponse", targetNamespace = "http://com", className = "com.ConvertFeetToMilesResponse")
    public double convertFeetToMiles(
        @WebParam(name = "value", targetNamespace = "http://com")
        double value);

    /**
     * 
     * @param value
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(name = "convertWeeksToYearsReturn", targetNamespace = "http://com")
    @RequestWrapper(localName = "convertWeeksToYears", targetNamespace = "http://com", className = "com.ConvertWeeksToYears")
    @ResponseWrapper(localName = "convertWeeksToYearsResponse", targetNamespace = "http://com", className = "com.ConvertWeeksToYearsResponse")
    public double convertWeeksToYears(
        @WebParam(name = "value", targetNamespace = "http://com")
        double value);

    /**
     * 
     * @param value
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(name = "convertInchesToFeetReturn", targetNamespace = "http://com")
    @RequestWrapper(localName = "convertInchesToFeet", targetNamespace = "http://com", className = "com.ConvertInchesToFeet")
    @ResponseWrapper(localName = "convertInchesToFeetResponse", targetNamespace = "http://com", className = "com.ConvertInchesToFeetResponse")
    public double convertInchesToFeet(
        @WebParam(name = "value", targetNamespace = "http://com")
        double value);

    /**
     * 
     * @param value
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(name = "convertInchesToCentimeterReturn", targetNamespace = "http://com")
    @RequestWrapper(localName = "convertInchesToCentimeter", targetNamespace = "http://com", className = "com.ConvertInchesToCentimeter")
    @ResponseWrapper(localName = "convertInchesToCentimeterResponse", targetNamespace = "http://com", className = "com.ConvertInchesToCentimeterResponse")
    public double convertInchesToCentimeter(
        @WebParam(name = "value", targetNamespace = "http://com")
        double value);

    /**
     * 
     * @param value
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(name = "convertFeetToMeterReturn", targetNamespace = "http://com")
    @RequestWrapper(localName = "convertFeetToMeter", targetNamespace = "http://com", className = "com.ConvertFeetToMeter")
    @ResponseWrapper(localName = "convertFeetToMeterResponse", targetNamespace = "http://com", className = "com.ConvertFeetToMeterResponse")
    public double convertFeetToMeter(
        @WebParam(name = "value", targetNamespace = "http://com")
        double value);

    /**
     * 
     * @param value
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(name = "convertDaysToMonthsReturn", targetNamespace = "http://com")
    @RequestWrapper(localName = "convertDaysToMonths", targetNamespace = "http://com", className = "com.ConvertDaysToMonths")
    @ResponseWrapper(localName = "convertDaysToMonthsResponse", targetNamespace = "http://com", className = "com.ConvertDaysToMonthsResponse")
    public double convertDaysToMonths(
        @WebParam(name = "value", targetNamespace = "http://com")
        double value);

}
